import { Metadata } from "next";

export const metadata: Metadata = {
    title: "DoclessAI - Registration",
    description: "Generated by create next app",
};

export default function RegistrationLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <div>
            {children}
        </div>
    );
}

