import { Metadata } from "next";

export const metadata: Metadata = {
    title: "DoclessAI - Login",
    description: "Generated by create next app",
};

export default function LoginLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <div>
            {children}
        </div>
    );
}

